name: evira_e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  app_settings: ^6.1.1
  build_runner: ^2.7.0
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fade_shimmer: ^2.4.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_gen_runner: ^5.11.0
  flutter_holo_date_picker: ^2.0.0
  flutter_localization: ^0.3.3
  flutter_multi_formatter: ^2.13.10
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.10.0
  get_it: ^8.2.0
  go_router: ^16.2.0
  go_transitions: ^0.8.2
  google_fonts: ^6.3.0
  group_button: ^5.3.4
  image_picker: ^1.2.0
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  intl: ^0.20.2
  intl_utils: ^2.8.11
  loading_animation_widget: ^1.3.0
  local_auth: ^2.3.0
  lottie: ^3.3.2
  otp_resend_timer: ^1.0.0
  pattern_formatter: ^4.0.1
  pinput: ^5.0.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.10.1
  toastification: ^3.0.3
  app_links: ^6.4.1
  google_sign_in: ^7.2.0
  internet_connection_checker_plus: ^2.9.0
  my_flutter_toolkit:
    git:
      url: https://github.com/AmrSalahDev/MyFlutterToolKit.git
      ref: main
  carousel_slider: ^5.1.1
  bloc_test: ^10.0.0
  connectivity_plus: ^7.0.0
  mockito: ^5.5.0
  thanos_snap_effect: ^0.0.9
  animated_emoji: ^3.2.1
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.3.0
 
  infinite_scroll_pagination: ^5.1.1
  flutter_sticky_header: ^0.8.0
  animated_hint_textfield: ^1.1.1
  animation_list: ^3.1.0
  dismissible_page: ^1.0.2
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.5
  animated_digit: ^3.3.2
  talker_bloc_logger: ^5.0.2
  stream_transform: ^2.1.1
  retry: ^3.1.2
  visibility_detector: ^0.4.0+2
  bloc_concurrency: ^0.3.0
  readmore: ^3.0.0
  permission_handler: ^12.0.1
  contacts_service_plus: ^0.0.2
  url_launcher: ^6.3.2
  expansion_tile_card: ^3.0.0
  grouped_list: ^6.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  animate_do: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: true

flutter_intl:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  class_name: EviraLang # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/core/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/core/lang_generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: true # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false

flutter:
  uses-material-design: true
  shaders:
    - packages/thanos_snap_effect/shader/thanos_snap_effect.glsl

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/splash/
    - assets/icons/
    - assets/lotties/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
